/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decode_rs_interleaved.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ffac9f53d6c13ca17eb384567a17e198)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/decode_rs_interleaved.h>
// pydoc.h is automatically generated in the build directory
#include <decode_rs_interleaved_pydoc.h>

void bind_decode_rs_interleaved(py::module& m)
{

    using decode_rs_interleaved    = ::gr::satellites::decode_rs_interleaved;


    py::class_<decode_rs_interleaved, gr::block, gr::basic_block,
        std::shared_ptr<decode_rs_interleaved>>(m, "decode_rs_interleaved", D(decode_rs_interleaved))

        .def(py::init(&decode_rs_interleaved::make),
           py::arg("verbose"),
           py::arg("basis"),
           py::arg("codewords"),
           D(decode_rs_interleaved,make)
        )
        



        ;




}







