/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decode_rs_general.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(67dc14d6e8282f04b2f23e1b2b9d1b61)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/decode_rs_general.h>
// pydoc.h is automatically generated in the build directory
#include <decode_rs_general_pydoc.h>

void bind_decode_rs_general(py::module& m)
{

    using decode_rs_general    = ::gr::satellites::decode_rs_general;


    py::class_<decode_rs_general, gr::block, gr::basic_block,
        std::shared_ptr<decode_rs_general>>(m, "decode_rs_general", D(decode_rs_general))

        .def(py::init(&decode_rs_general::make),
           py::arg("gfpoly"),
           py::arg("fcr"),
           py::arg("prim"),
           py::arg("nroots"),
           py::arg("verbose"),
           D(decode_rs_general,make)
        )
        



        ;




}







